version: '3.8'
services: 
  db:
    image: postgres:14.8
    restart: always
    env_file:
      - ./env/postgres
      - ./env/${APP_MODE}/app_database
    ports:
      - '${CHAT_POSTGRES_PORT}:5432'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/sql
      - ./docker/postgres/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
