version: '3.8'
services: 
  web_app:
    container_name: 'chat-server'
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CHAT_POSTGRES_HOST: '172.17.0.1'
      CHAT_POSTGRES_PORT: ${CHAT_POSTGRES_PORT:-5431}
    env_file:
      - ./env/${APP_MODE:-dev}/app_database
    ports:
      - '3000:3000'
  db:
    image: postgres:14.8
    restart: always
    env_file:
      - ./env/postgres
      - ./env/${APP_MODE:-dev}/app_database
    ports:
      - '${CHAT_POSTGRES_PORT:-5431}:5432'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/sql
      - ./docker/postgres/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
